# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 575ecd78742718ec5875bd431eb913a4639b4cb486e4c6e2b8dc902265e277aa396c8dec7db578dc7cf4a322b294ebef9ae71bf57def7d4fed5e6902633e43f5

test:
  secret_key_base: 99208c00a2a4c273c38f61a9fe643a3c6fbee6af561f25e75538dd48276f52c7d2ffd3a56a3661bb524c9339b82ccb27fc74406c783942c8830bbe33abec9bd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
